[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

lib_deps =
    bblanchon/ArduinoJson

monitor_speed = 921600
upload_port = COM3
monitor_port = COM3
monitor_filters = esp32_exception_decoder

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -I src